updated

diff --git a/ci/test.yml b/ci/test.yml
--- a/ci/test.yml
+++ b/ci/test.yml
@@ -22,5 +22,23 @@ run:
       cd sampleproduct-1-web/acceptance_tests
       ls
       npm install
-      npm test
+      cd mochawesome-report
       ls
+      apt-get update
+      apt-get install -y zip
+      zip -r $appname.war .
+      appstatus=$(curl --silent -u $managerusername:$managerpassword "$managerurl/list" | grep $appname)
+      if [ ! -z "$appstatus" ]; then
+      	echo "Undeploying $appname $managerurl/text/undeploy?path=/$appname .."
+      	UNDEPLOY_STATUS=$(curl -v -u $managerusername:$managerpassword "$managerurl/undeploy?path=/$appname" | head -n1)
+
+      	if [[ $UNDEPLOY_STATUS == OK* ]]; then
+      		echo "Undeploy Completed, hence deploying unit test results .."
+      	else
+      		echo "Undeploy failed .."
+      		exit 1
+      	fi
+      else
+      	echo "$appname is not up and running, hence deploying unit test results .."
+      fi
+      curl -v -u $managerusername:$managerpassword -T $appname.war "$managerurl/deploy?path=/$appname"
